name: melora_music
description: "Melora Music Player - Modern Offline & Online Music Player"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Audio
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  audio_service: ^0.18.12
  audio_session: ^0.1.18
  on_audio_query: ^2.9.0

  # UI & Design
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  palette_generator: ^0.3.3+4
  glassmorphism_ui: ^0.3.0
  iconsax_flutter: ^1.0.0+1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  smooth_page_indicator: ^1.1.0
  marquee: ^2.2.3
  sleek_circular_slider: ^2.0.1

  # Navigation
  go_router: ^13.0.1

  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  path: ^1.8.3

  # Permissions
  permission_handler: ^11.1.0

  # Connectivity
  connectivity_plus: ^5.0.2

  # Utils
  intl: ^0.19.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  package_info_plus: ^9.0.0
  flutter_local_notifications: ^17.0.0
  rxdart: ^0.27.7
  equatable: ^2.0.5
  uuid: ^4.2.2

  # Splash
  flutter_native_splash: ^2.3.8
  file_picker: ^8.3.7
  audiotags: ^1.4.5
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/fonts/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#0D0D0F"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  android_12:
    color: "#0D0D0F"
    image: assets/images/splash_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"
  remove_alpha_ios: true
